<div class="main">
    <div class="layer">
        <div class="image-1">
            <?php
                echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('image-1')
                ->toHtml();
            ?>
                <?php
                    echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('link-1')
                    ->toHtml();
                ?>
        </div>
        <div class="image-2" >
            <?php
                echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('image-2')
                ->toHtml();
            ?>
                <?php
                    echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('link-2')
                    ->toHtml();
                ?>
        </div>
    </div>
    <div class="layer">
        <div class="image-3" >
            <?php
                echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('image-3')
                ->toHtml();
            ?>
                <?php
                    echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('link-3')
                    ->toHtml();
                ?>
        </div>
        <div class="image-4">
            <?php
                echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('image-4')
                ->toHtml();
            ?>
                <?php
                    echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('link-4')
                    ->toHtml();
                ?>
        </div>
    </div>
    <div class="layer">
        <div class="image-5">
            <?php
                echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('image-5')
                ->toHtml();
            ?>
            <?php
                echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('link-5')
                ->toHtml();
            ?>
        </div>
        <div class="image-6">
            <?php
                echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('image-6')
                ->toHtml();
            ?>
                <?php
                    echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('link-6')
                    ->toHtml();
                ?>
        </div>
        <div class="image-7">
            <?php
                echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('image-7')
                ->toHtml();
                ?>
            <?php
                    echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('link-7')
                    ->toHtml();
                ?>
        </div>
</div>
