<div class="header-link">
		<table class="header-table">
		<tr>
			<td><a href="#"><?= /* @escapeNotVerified */ __('Help') ?></a></td>
			<td class="width"><a href="#"><?= /* @escapeNotVerified */ __('Contact') ?></a></td>
			<td><a href="#"><?= /* @escapeNotVerified */ __('Delivery Information') ?></a></td>
		</tr>
	</table>
    <!-- <div class="call">
        <span><img class="header-call" src="<?php echo $this->getViewFileUrl("images/header-call.png");?>"/><?= /* @escapeNotVerified */ __('Call us : 032 2352 782') ?></span>
    </div> -->
</div>